version: '3.8'

services:
  # Cancer Alpha API Service
  cancer-alpha-api:
    image: cancer-alpha/api:latest
    container_name: cancer-alpha-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - api_logs:/app/logs
      - model_cache:/app/model_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: cancer-alpha-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  api_logs:
    driver: local
  model_cache:
    driver: local
  redis_data:
    driver: local
