#!/bin/bash

# Cancer Alpha - React Web App Demo Information
# This is a demonstration version - full React app requires separate licensing
# For production web application access, contact craig.stillwell@gmail.com

echo "⚛️  Cancer Alpha - React Web App Demo Information"
echo "================================================"
echo ""
echo "⚠️  DEMO VERSION NOTICE:"
echo "This public repository contains demonstration code only."
echo "The full production React web application requires separate patent licensing."
echo ""
echo "📋 What's Available in This Demo:"
echo "  • Interactive Streamlit interface (run: ./start_streamlit.sh)"
echo "  • Downloadable demo package with synthetic data"
echo "  • Educational cancer classification examples"
echo "  • Basic web-based AI interaction"
echo ""
echo "🏥 Production React Web App Features (Not in Demo):"
echo "  • Modern clinical interface with genomic data exploration"
echo "  • Advanced visualization dashboards"
echo "  • Real-time cancer classification with 99.5% accuracy"
echo "  • Multi-modal data integration interface"
echo "  • Clinical decision support tools"
echo "  • Hospital IT system integration"
echo "  • HIPAA-compliant security measures"
echo "  • Professional patient data management"
echo ""
echo "💼 Commercial Licensing:"
echo "  • Email: craig.stillwell@gmail.com"
echo "  • Subject: 'Cancer Alpha React App License Inquiry'"
echo "  • Include: Intended use case and organization details"
echo ""
echo "📖 Academic Use:"
echo "  • The demo version is available for academic research"
echo "  • Proper citation and attribution required"
echo "  • No redistribution or commercial use"
echo ""
echo "🚀 To try the available demo interface:"
echo "     ./start_streamlit.sh"
echo ""
echo "📚 Documentation:"
echo "  • Web App Features Guide: docs/WEB_APP_FEATURES_GUIDE.md"
echo "  • API Reference Guide: docs/API_REFERENCE_GUIDE.md"
echo "  • Master Installation Guide: MASTER_INSTALLATION_GUIDE.md"
echo ""
echo "🔗 Demo Package Download:"
echo "     https://github.com/rstil2/cancer-alpha/raw/main/cancer_genomics_ai_demo.zip"
