#!/bin/bash

# Oncura - Demo API Information
# This is a demonstration version - full API requires separate licensing
# For production API access, contact craig.stillwell@gmail.com

echo "🔌 Oncura - API Demo Information"
echo "======================================"
echo ""
echo "⚠️  DEMO VERSION NOTICE:"
echo "This public repository contains demonstration code only."
echo "The full production API requires separate patent licensing."
echo ""
echo "📋 What's Available in This Demo:"
echo "  • Interactive Streamlit interface (run: ./start_streamlit.sh)"
echo "  • Downloadable demo package with synthetic data"
echo "  • Educational cancer classification examples"
echo ""
echo "🏥 Production API Features (Not in Demo):"
echo "  • REST API with comprehensive endpoints"
echo "  • Real genomic data processing"
echo "  • 99.5% accuracy ensemble models"
echo "  • Clinical-grade security and compliance"
echo "  • Hospital system integration"
echo "  • Multi-modal transformer architectures"
echo ""
echo "💼 Commercial Licensing:"
echo "  • Email: craig.stillwell@gmail.com"
echo "  • Subject: 'Oncura API License Inquiry'"
echo "  • Include: Intended use case and organization details"
echo ""
echo "📖 Academic Use:"
echo "  • The demo version is available for academic research"
echo "  • Proper citation and attribution required"
echo "  • No redistribution or commercial use"
echo ""
echo "🚀 To try the available demo:"
echo "     ./start_streamlit.sh"
echo ""
echo "📚 For more information:"
echo "     • README.md - Complete project overview"
echo "     • PATENTS.md - Patent and licensing details"
echo "     • docs/ - Additional documentation"
