global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "cancer_alpha_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Cancer Alpha API
  - job_name: 'cancer-alpha-api'
    static_configs:
      - targets: ['cancer-alpha-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Cancer Alpha Web
  - job_name: 'cancer-alpha-web'
    static_configs:
      - targets: ['cancer-alpha-web:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
