apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-alpha-api
  namespace: cancer-alpha
  labels:
    app: cancer-alpha-api
    version: v1.0.0
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cancer-alpha-api
  template:
    metadata:
      labels:
        app: cancer-alpha-api
        version: v1.0.0
        component: backend
    spec:
      containers:
      - name: cancer-alpha-api
        image: cancer-alpha/api:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: REDIS_URL
          value: "redis://cancer-alpha-redis:6379"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: model-cache
          mountPath: /app/model_cache
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: cancer-alpha-model-cache
      - name: logs
        persistentVolumeClaim:
          claimName: cancer-alpha-api-logs
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: cancer-alpha-api-service
  namespace: cancer-alpha
  labels:
    app: cancer-alpha-api
spec:
  selector:
    app: cancer-alpha-api
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cancer-alpha-model-cache
  namespace: cancer-alpha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cancer-alpha-api-logs
  namespace: cancer-alpha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
