apiVersion: v1
kind: Namespace
metadata:
  name: cancer-alpha
  labels:
    name: cancer-alpha
    environment: production
    project: cancer-alpha
    version: v1.0.0
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cancer-alpha-quota
  namespace: cancer-alpha
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cancer-alpha-limits
  namespace: cancer-alpha
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "5Gi"
    type: PersistentVolumeClaim
