apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-alpha-web
  namespace: cancer-alpha
  labels:
    app: cancer-alpha-web
    version: v1.0.0
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cancer-alpha-web
  template:
    metadata:
      labels:
        app: cancer-alpha-web
        version: v1.0.0
        component: frontend
    spec:
      containers:
      - name: cancer-alpha-web
        image: cancer-alpha/web:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://cancer-alpha-api-service:8000"
        - name: REACT_APP_ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: cancer-alpha-web-logs
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: cancer-alpha-web-service
  namespace: cancer-alpha
  labels:
    app: cancer-alpha-web
spec:
  selector:
    app: cancer-alpha-web
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cancer-alpha-web-logs
  namespace: cancer-alpha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
